### ISSUE TITLE
Segfault when num_neighbors is more than about 510

### ISSUE THREAD

**Issue by vasu20** [ke-li/dci-knn#1]
Hi Ke

Thanks for making your code available.  Very interesting work.  

I was playing with the python API and it turns out that if I select num_neighbors as anything more than 511 I get a seg fault.  Could you check when you get a chance?  Thanks

```
Generating Data... 
Took 0.2199s
Constructing Data Structure... 
Took 0.1833s
Querying... 

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

These are the parameters used:
```
    dim = 1024  # Dimensionality of data
    intrinsic_dim = 1024  # Intrinsic dimensionality of data
    num_points = 10000  # Number of data points
    num_queries = 1  # Number of queries
    num_neighbours = 512  # The k in k-NN
```

**Comment by ke-li** [comment]
Hi Vasu,

The issue should be fixed now. Can you pull the latest version and give it another try?

**Comment by vasu20** [comment]
Hi Ke

This works! Thank you for fixing.

Vasu
